[mypy]
mypy_path = integratie
[mypy]
mypy_path = integratie
exclude = integratie/tools/
explicit_package_bases = True

[mypy-pika]
ignore_missing_imports = True

[mypy-pika.*]
ignore_missing_imports = True

[mypy-defusedxml]
ignore_missing_imports = True

[mypy-defusedxml.*]
ignore_missing_imports = True