[mypy]
mypy_path = integratie
exclude = integratie/tools/
explicit_package_bases = True
namespace_packages = True

[mypy-pika]
ignore_missing_imports = True

[mypy-pika.*]
ignore_missing_imports = True

[mypy-defusedxml]
ignore_missing_imports = True

[mypy-defusedxml.*]
ignore_missing_imports = True

[mypy-xmlrpc.*]
ignore_missing_imports = True

[mypy-integratie.sender]
ignore_missing_imports = True

[mypy-integratie.receiver]
ignore_missing_imports = True

[mypy-integratie.monitoring]
ignore_missing_imports = True

[mypy-integratie.config_utils]
ignore_missing_imports = True

[mypy-integratie.typing_utils]
ignore_missing_imports = True

[mypy-integratie.order_poller]
ignore_missing_imports = True

[mypy-integratie.odoo_setup]
ignore_missing_imports = True

[mypy-integratie.pos_profiles]
ignore_missing_imports = True

