[mypy]
exclude = integratie/tools/

[mypy-pika]
ignore_missing_imports = True

[mypy-pika.*]
ignore_missing_imports = True

[mypy-defusedxml]
ignore_missing_imports = True

[mypy-defusedxml.*]
ignore_missing_imports = True